AllCops:
  NewCops: enable

Layout/EndOfLine:
  Enabled: false

Style/Documentation:
  Enabled: false

Lint/EmptyClass:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Layout/LineLength:
  Enabled: false